### PR TITLE
Update version information to 1.5.3

### PR DESCRIPTION
**Pull request by Brett208**
- Add file resource information to improve traceability of version numbers between releases and ease future troubleshooting

NetHelper.rc is readable in text editor if anyone wants to review it. Not sure why GitHub labeled as such.

-Brett

### CODE REVIEW

**Comment by DanRStevens** [comment]
Ahh, the file uses UTF-16 encoding. That means every other byte is 0, and according to the StackOverflow answer to [How to determine if Git handles a file as binary or as text?](https://stackoverflow.com/questions/6119956/how-to-determine-if-git-handles-a-file-as-binary-or-as-text), Git detect a binary file by the present of a 0 byte within the first 8000 bytes.

Another point worth mentioning, is the presence of the BOM (Byte Order Mark). The file starts with bytes FF FE, which implies UTF-16 in little endian byte order.

**Comment by Brett208** [comment]
Thanks for commenting on the details. I was going to fix this by adding a gitattribute file, but it looks like it gets pretty dicey.

> working-tree-encoding
> 
> Git recognizes files encoded in ASCII or one of its supersets (e.g. UTF-8, ISO-8859-1, …​) as text files. Files encoded in certain other encodings (e.g. UTF-16) are interpreted as binary and consequently built-in Git text processing tools (e.g. git diff) as well as most Git web front ends do not visualize the contents of these files by default.
> 
> In these cases you can tell Git the encoding of a file in the working directory with the working-tree-encoding attribute. If a file with this attribute is added to Git, then Git reencodes the content from the specified encoding to UTF-8. Finally, Git stores the UTF-8 encoded content in its internal data structure (called "the index"). On checkout the content is reencoded back to the specified encoding.
> 
> Please note that using the working-tree-encoding attribute may have a number of pitfalls:
> 
>Alternative Git implementations (e.g. JGit or libgit2) and older Git versions (as of March 2018) do not support the working-tree-encoding attribute. If you decide to use the working-tree-encoding attribute in your repository, then it is strongly recommended to ensure that all clients working with the repository support it.
> 
>    For example, Microsoft Visual Studio resources files (`*.rc`) or
>    PowerShell script files (`*.ps1`) are sometimes encoded in UTF-16.
>    If you declare `*.ps1` as files as UTF-16 and you add `foo.ps1` with
>    a `working-tree-encoding` enabled Git client, then `foo.ps1` will be
>    stored as UTF-8 internally. A client without `working-tree-encoding`
>    support will checkout `foo.ps1` as UTF-8 encoded file. This will
>    typically cause trouble for the users of this file.
> 
>     If a Git client, that does not support the `working-tree-encoding`
>     attribute, adds a new file `bar.ps1`, then `bar.ps1` will be
>     stored "as-is" internally (in this example probably as UTF-16).
>     A client with `working-tree-encoding` support will interpret the
>     internal contents as UTF-8 and try to convert it to UTF-16 on checkout.
>     That operation will fail and cause an error.
> 
>Reencoding content to non-UTF encodings can cause errors as the conversion might not be UTF-8 round trip safe. If you suspect your encoding to not be round trip safe, then add it to core.checkRoundtripEncoding to make Git check the round trip encoding (see git-config[1]). SHIFT-JIS (Japanese character set) is known to have round trip issues with UTF-8 and is checked by default.
> 
>Reencoding content requires resources that might slow down certain Git operations (e.g git checkout or git add).
> 
>Use the working-tree-encoding attribute only if you cannot store a file in UTF-8 encoding and if you want Git to be able to process the content as text.
> 
>As an example, use the following attributes if your *.ps1 files are UTF-16 encoded with byte order mark (BOM) and you want Git to perform automatic line ending conversion based on your platform.
> 
> *.ps1		text working-tree-encoding=UTF-16
> 
> Use the following attributes if your *.ps1 files are UTF-16 little endian encoded without BOM and you want Git to use Windows line endings in the working directory. Please note, it is highly recommended to explicitly define the line endings with eol if the working-tree-encoding attribute is used to avoid ambiguity.
> 
> *.ps1		text working-tree-encoding=UTF-16LE eol=CRLF

**Comment by Brett208** [comment]
I just did a FORCE PUSH that deleted 2 bad commits to this branch. If you downloaded them, you will need to delete your local branch and re-download.

-Brett

**Comment by DanRStevens** [comment]
Aha, a force push. Welcome to the dark side! :wink:

Thank you for the details. If I remember correctly, re-encoding the source file as UTF-8 may cause the resource compiler to fail on it. Doesn't look like there is a nice solution.

**Pull request merged**
