### PR TITLE
Copy PDB file during post build event script for debugging purposes

### PR DESCRIPTION
**Pull request by Brett208**

### CODE REVIEW

**Comment by DanRStevens** [comment]
Hmm, would it make more sense to specify the location of the PDB file in the project debug settings, rather than copying it around?

I found some details that include the search order for PDB files.
Reference: [Specify symbol (.pdb) and source files in the Visual Studio debugger](https://docs.microsoft.com/en-us/visualstudio/debugger/specify-symbol-dot-pdb-and-source-files-in-the-visual-studio-debugger?view=vs-2017)

**Comment by Brett208** [comment]
Just tested this. Turns out Visual Studio is smart enough to find the PDB file without copying it or changing any project settings. Not sure why I was thinking that I needed to copy the PDB file?

So, even though Outpost 2 is loading the DLL from the NetHelper directory, if Outpost 2 is attached to the debugger via the NetHelper Visual Studio project, Visual Studio will automatically pull the debug or release compiled symbols from the appropriate Debug or Release directory.

Thanks for pointing that out.

-Brett

**Review by DanRStevens — APPROVED** [review]
Ahh, glad to hear it's that easy.

I looked up the `xcopy` commands. For reference:
`/y` - Don't prompt for overwrite
`/d` - Only copy if source is newer than destination

I wasn't aware of the `/d` option. That's a nice little speed optimization if the file isn't updated.

I'm curious now. Does the post-build step run even when there are no updates? If there are trivial updates (say whitespace changes) that cause a recompile, but no actual changes, does the output file timestamp change? I'm guessing there are conditions which allow the copy to be skipped.

**Comment by Brett208** [comment]
Dan,

Just tested. Whitespace changes or force recompile will update the file date and cause the cop to happen.

This is just saving copies if you click compile, but the compiler sees no changes to the source code to actually compile. It would probably be more helpful when copying a readme file or something similar. 

I like using xcopy because it tends to report errors better.

-Brett

**Comment by DanRStevens** [comment]
Ahh, sounds like the post compile step still runs even if there was nothing new to compile. I wasn't certain about that. Ok, curiosity satisfied.

**Pull request merged**
