### PR TITLE
Update deprecated calls

### LINKED ISSUE #2: Remove deprecated WINSOCK calls
VS2017's toolset is calling the functions inet_addr and inet_ntoa as deprecated. Should look at switching to different function calls to protect from future problems.

Warning	C4996	'inet_ntoa': Use inet_ntop() or InetNtop() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings	NetHelper	\nethelper\src\portforward.cpp	174	

Warning	C4996	'inet_addr': Use inet_pton() or InetPton() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings	NetHelper	\nethelper\src\portforward.cpp	258

### PR DESCRIPTION
**Pull request by DanRStevens**
I just realized this project doesn't have CI builds setup. This code will need to be tested before merging.

Assuming the code is good, this should close #2.

### CODE REVIEW

**Comment by Brett208** [comment]
Dan, 

Thanks for putting time into this. I'll pull, compile, and test when I have some time and let you know how it goes.

It would be nice to bring in appveyor or some other CI. Now that we have the Libnatpmp and miniupnp building consistently, I suppose this is actually possible now. 

-Brett

**Comment by Brett208** [comment]
I merged the master into this branch to ease troubleshooting with the new submodules and project settings.

It has at least one problem on MSVC. 

Line 24 of PortForward.h contains:
``` C++
  static char internalIp[46],
              externalIp[46];
```

Also, it appears that INET6_ADDRSTRLEN is not defined by the current includes. If we add the header 
`#include <ws2tcpip.h>` I think it will work. This might be being complicated by adding Windows Lean and Mean, not sure.

-Brett

**Comment by DanRStevens** [comment]
Hmm, that header looks Windows specific. I'm not certain of the correct header for that constant, and how the header might vary by platform.

Maybe we should roll back that one commit, or split the commits into separate branches. That change is rather isolated from the rest.

**Comment by DanRStevens** [comment]
Ok, here's a more minimal change set to address the current Issue. The extra stuff has been moved to another branch, so it can be fixed and applied independently.

**Comment by Brett208** [comment]
I added the Windows header containing inet_ntop and inet_pton.

Tested NetHelper by compiling and having someone else join a game chat room via TCP/IP successfully. Also noted that NetHelper was showing my external IP address before hosting the game.

Recommend that we merge this branch. Then merge the new master branch into PR #12 so it contains the header ws2tcpip.h. This header should also contain INET6_ADDRSTRLEN. I can test PR #12 when this is done.

-Brett

**Review by Brett208 — APPROVED** [review]

**Comment by Brett208** [comment]
Also, I had to delete my local copy of this branch and then re-download it to get changes. I suspect the public history was modified. If you want to squash my last 2 commits, might be nice to remove the noise of adding the include commented out and then un-commenting it. Pushed too early. :/

**Comment by DanRStevens** [comment]
Yes, I modified the history when I split the other commit to a new branch. I also rebased on the current master, so the merge wouldn't be needed. Both operations rewrote history on the branch. I can merge your two commits you did if you'd like.

I suppose technically I'm being dishonest here about how development actually happened. I'm also being a bit of a pain, forcing you to delete and redownload branches. Probably why so many people recommend not rewriting public history.

----

Thank you for the header update. I didn't realize that header file was needed for the new methods. I thought it was only related to the constant.

**Pull request merged**
